name: Deploy KDS
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Secret
        run: |
          sed -i 's|PROD_ZAPIER_URL_PLACEHOLDER|${{ secrets.ZAPIER_WEBHOOK_URL }}|g' kds/app.js
          sed -i "s|FIREBASE_API_KEY_PLACEHOLDER|${{ secrets.FIREBASE_API_KEY }}|g" kds/app.js
          sed -i "s|FIREBASE_DB_URL_PLACEHOLDER|${{ secrets.FIREBASE_DB_URL }}|g" kds/app.js
          sed -i "s|FIREBASE_AUTH_DOMAIN_PLACEHOLDER|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" kds/app.js
          sed -i "s|FIREBASE_APP_ID_PLACEHOLDER|${{ secrets.FIREBASE_APP_ID }}|g" kds/app.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder your index.html is in
